repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bandit~=2.1 # renovate: follow
          - flake8-bugbear~=20.1 # renovate: follow
          - flake8-comprehensions~=3.3 # renovate: follow
          - flake8-docstrings~=1.5 # renovate: follow
          - flake8-unused-arguments~=0.0 # renovate: follow
          - pep8-naming~=0.11 # renovate: follow
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        additional_dependencies:
          - aiohttp~=3.7.2 # renovate: follow
          - pydantic~=1.7.1 # renovate: follow
          - pytest~=6.1 # renovate: follow
          - pytest-mock~=3.3 # renovate: follow
          - typer~=0.3.2 # renovate: follow
