[tool.poetry]
name = "opcua-graphql-bridge"
version = "0.1.0"
description = ""
authors = ["Arnaud Rocher <arnaud.roche3@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pre-commit = "^2.3.0"
flake8 = "^3.7.9"
pylint = "^2.5.0"
isort = "^4.3.21"
flake8-comprehensions = "^3.2.2"
pep8-naming = "^0.10.0"
flake8-bugbear = "^20.1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
