[tool.poetry]
name = "opcua-webhmi-bridge"
version = "0.1.0"
description = "Bridge between OPC-UA server and web-based HMI"
authors = ["Arnaud Rocher <arnaud.roche3@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
asyncua = { git="https://github.com/FreeOpcUa/opcua-asyncio.git", rev="5132c4ed" }
websockets = "^8.1"
typed-argument-parser = "^1.4.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
isort = "^4.3.21"
flake8-comprehensions = "^3.2.2"
pep8-naming = "^0.10.0"
flake8-bugbear = "^20.1.4"
bandit = "^1.6.2"
flake8-unused-arguments = "^0.0.3"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
