[tool.poetry]
name = "opcua-webhmi-bridge"
version = "0.1.0"
description = "Bridge between OPC-UA server and web-based HMI"
authors = ["Arnaud Rocher <arnaud.roche3@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
opcua-agent = "opcua_webhmi_bridge.main:app"

[tool.poetry.dependencies]
python = "^3.8"
asyncua = "^0.8.3"
tenacity = "^6.2.0"
aioinflux = "^0.9.0"
pydantic = {extras = ["dotenv"], version = "^1.6.1"}
typer = "^0.3.2"
aiohttp = "^3.6.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.6.4"
flake8-comprehensions = "^3.3.0"
pep8-naming = "^0.11.1"
flake8-bugbear = "^20.1.4"
bandit = "^1.6.2"
flake8-unused-arguments = "^0.0.6"
mypy = "^0.790"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
