on:
  push:
    branches:
      - main

name: Automated release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: python
          package-name: opcua-webhmi-bridge
