name: Tests and code coverage

env:
  PYTHON_VERSION: "3.8"
  POETRY_INSTALLER_URL: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up Poetry cache for Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: poetry-
    - name: Install Poetry
      run: |
        curl -sSL $POETRY_INSTALLER_URL | python - --yes
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Test with pytest
      run: |
        poetry run pytest -vv --cov=opcua_webhmi_bridge --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
