name: Tests and code coverage

env:
  PYTHON_VERSION: "3.8"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Set up Poetry cache for Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: poetry-
    - name: Install Poetry
      run: |
        source poetry_install_vars.sh
        curl -sSL -o get-poetry.py "$POETRY_URL"
        python get-poetry.py --yes --no-modify-path --version="$POETRY_VERSION"
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Test with pytest
      run: |
        poetry run pytest -vv --cov=opcua_webhmi_bridge --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
